// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    NumberScroll: typeof import('./src/components/NumberScroll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollNumber: typeof import('./src/components/ScrollNumber.vue')['default']
    ScrollNumberItem: typeof import('./src/components/ScrollNumberItem.vue')['default']
    SlotMachine: typeof import('./src/components/SlotMachine.vue')['default']
    SlotMachineScrollNumber: typeof import('./src/components/SlotMachineScrollNumber.vue')['default']
    SlotReel: typeof import('./src/components/SlotReel.vue')['default']
    YetAnotherSlotReel: typeof import('./src/components/YetAnotherSlotReel.vue')['default']
  }
}
